[package]
name = "gecs"
version = "0.3.0"
authors = ["recatek"]
description = "A generated entity component system."
edition = "2021"
repository = "https://github.com/recatek/gecs"
license = "MIT OR Apache-2.0"
readme = "README.md"
keywords = ["ecs", "entity"]
categories = ["data-structures", "game-engines"]

[features]
default = []
32_components = []
# Wrap rather than panic when an slot version overflows (used for entity handles).
wrapping_entity_version = []
# Wrap rather than panic when an archetype version overflows (used for raw entities).
wrapping_entity_raw_version = []

[dependencies]
gecs_macros = { version = "0.3.0", path = "macros", default_features = false }

seq-macro = { version = "0.3.5" } # For building "variadic" storage
