[package]
name = "gecs"
version = "0.1.2"
authors = ["recatek"]
description = "A generated entity component system."
edition = "2021"
repository = "https://github.com/recatek/gecs"
license = "MIT OR Apache-2.0"
readme = "README.md"
keywords = ["ecs", "entity"]
categories = ["data-structures", "game-engines"]

[features]
default = []
32_components = []

[dependencies]
gecs_macros = { version = "0.1.2", path = "macros" }

seq-macro = { version = "0.3" } # For building "variadic" storage
